# Generated by Django 3.2.12 on 2022-02-26 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, verbose_name='Название товара')),
                ('type', models.CharField(choices=[('phone', 'Телефон'), ('tv', 'Телевизор'), ('computer', 'Компьютер')], max_length=50, verbose_name='Тип')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('file', models.FileField(blank=True, null=True, upload_to='orders/', verbose_name='Файл')),
            ],
            options={
                'ordering': ['delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес пункта выдачи')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
